# Generated by Django 5.2.6 on 2025-11-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Inistitution Name')),
                ('county', models.CharField(max_length=100)),
                ('sch', models.ManyToManyField(to='schools.school')),
            ],
        ),
    ]
