# Generated by Django 5.2.6 on 2025-11-14 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='sch',
        ),
        migrations.AddField(
            model_name='apartment',
            name='sch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
    ]
