# Generated by Django 5.2.6 on 2025-11-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_alter_school_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='county',
        ),
        migrations.AddField(
            model_name='apartment',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
