# Generated by Django 5.2.6 on 2025-11-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_remove_apartment_county_apartment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='rent',
            field=models.CharField(default='2000', max_length=100, verbose_name='Amount/Month'),
        ),
    ]
